[package]
name = "risp"
version = "0.1.0"
authors = ["Sean <seanchen11235@gmail.com>"]
edition = "2018"

[[bin]]
name = "risp"
path = "src/bin/main.rs"

[lib]
name = "risp"
path = "src/lib.rs"

[dependencies]
